// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tefjkdgyniebwanxyayg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZmprZGd5bmllYndhbnh5YXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODQ4MTYsImV4cCI6MjA3MTI2MDgxNn0.6lJ8z-slMmozBPpLEJHksh1Sbsstnr7amrRmP2Isybo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});